dbt_dwh:
  target: dev
  outputs:
    dev:
      dbname: elt_dwh
      host: postgres-dwh
      pass: airflow
      port: 5432
      threads: 4
      type: postgres
      user: airflow
      schema: public
    local:  
      dbname: elt_dwh
      host: localhost
      pass: airflow
      port: 5433
      threads: 4
      type: postgres
      user: airflow
      schema: public
